blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discord Server
    url: https://discord.gg/taghAqebzU
    about: |
      Chat with the community, ask questions and learn about best practices.
